language: php

dist: trusty

php:
  - 7.2

branches:
  only:
    [ master, develop ]

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS homestead DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;'

install:
  - travis_retry composer install --no-interaction --prefer-source
  - cp .env.travis .env
  - composer dump-autoload
  - php artisan migrate
  - php artisan db:seed

script: vendor/bin/phpunit
